### ISSUE TITLE
Ortho 7: group page, new  proteins section:  UI improvements

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#1123]
https://feature.orthomcl.org/orthomcl.feature/app/record/group/OG7_0000696

I know a few updates have been proposed but here some easy options  to improve the usability
- smaller pfam table with max height
---- located in middle or left
----  ideally header stays as you scroll
---- add search to reduce the domains
---- add sort

<img width="1441" alt="Screenshot 2024-06-27 at 3 47 13 PM" src="https://github.com/VEuPathDB/web-monorepo/assets/16354313/7849f1d0-6e25-4d29-9c34-ff4388434564">

**Comment by bobular** [comment]
I'd say this has all been superseded by @dmfalke's work on the filter drop-down buttons.

The request for a sticky table header was presumably just for the Pfam table that is no more. However, I had a think about adding this feature for the main table, but it's tricky to implement because of the tree. The tree isn't in a table cell/column. It's just next to the table. So I don't think that's going to happen unless we go back to the drawing board.

Closing this ticket.
