### ISSUE TITLE
Map filter table heading behaviour isn't right

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#135]
In a high-cardinality variable, like WWARN "Mutation group specific mutation linked to"

https://qa.restricted.clinepidb.org/ce.restricted.qa/app/maps/DS_24899fbd90
(open the filter menu item and navigate to this variable)

Typing in the search box causes a problematic state change/page refresh and the overlay variable choice is lost. Maybe the analysis state is getting hosed somehow?

In fact any interaction with filter table headings causes this

**Comment by adnauseum** [comment]
This will be resolved in https://github.com/VEuPathDB/web-monorepo/pull/154.

Note that this is unrelated to SAM. The specified behavior of the table is such that it has a "memory" for sort for a given variable. In the below screen case I sort Household Study Timepoint so that **Wave 7** is on top. I then navigate to Participant Study Timepoint and sort so that **Wave 10** is on top. When I return back to Household Study Timepoint, I should see **Wave 7** still on top, but I instead see the default order.

https://user-images.githubusercontent.com/24446573/236363355-cfa3e484-9933-404f-b798-bc4390b4d17a.mp4

In the case of the SAM this was causing a condition to evaluate true which unmounted the map component.
