### ISSUE TITLE
Differential abundance: include number of up/down regulated points in title or legend

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-monorepo#393]
From mbio meeting on 07/26. 

Dan B suggested it would be helpful to know how many points were red and how many were blue. One option is in the plot title. Another option would be to include the number in the legend. I'm leaning toward the legend since a person will already look there. Thoughts or other ideas? @dpbisme @jernestmyers ?

**Comment by asizemore** [comment]
just a note i there's a little extra work here because we are currently assigning color per point when drawing the point. We should probably move the color assigning function up a bit so that we loop through the data only once to both assign color and do any other things we do. Then, we can get a count of how many are red and blue.

**Comment by jernestmyers** [comment]
So here is a sort of base case mockup using some dev tools magic on [this branch](https://github.com/VEuPathDB/web-monorepo/pull/392):

![image](https://github.com/VEuPathDB/web-monorepo/assets/69446567/c48bf96f-5d75-4a6d-9e06-bc797a294c9a)

Couple thoughts:

1. What's the appropriate unit term? `x values`, `x points`, etc?
2. I recognize this base case mockup isn't great in that it's not easy to see/find the actual value, but better alternatives aren't jumping out to me. Whether for this work or not, we may want to refactor `PlotLegend` a wee bit so that the label property accepts a ReactNode instead of just a string. This would give us control over the style of the values, so we could make them bold or whatever to help them stand out.
3. Is it too weird to lead with the values, then the legend item? Something like `4 values - Inconclusive` and so on? In this case, the values would more or less line up cleanly (depending on the magnitude of each value).

**Comment by asizemore** [comment]
1. The approriate term uses the collections annotation `memberPlural`, but this isn't available for us just yet. It's in the eda-rbld db so it's possible if using the beta.mbio backend the annotations would be there? But even if they're not, i think `memberPlural ?? 'points'` makes sense.
2. Making them bold is a great idea! Let me ask dan what he thinks about the relative importance of these values.
3. OOoooh very clever. I could go either way on this one. I'll ping the dv group

**Comment by jernestmyers** [comment]
Great, I'm editing the original screenshot and I'll add a screenshot for the 3rd point as well.

**Comment by asizemore** [comment]
Based on the feedback in slack, let's do 
1. only add the number in parentheses 
2. number comes after label
3. If there is a `memberPlural` annotation (to be added later in #382 ), then we can render that in the legend title. Otherwise title is just "Legend".
