### ISSUE TITLE
Map - marker mouse-over popups are flashing every two seconds

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#616]
This is currently an issue on `main` on qa.vectorbase.org - in Firefox and Chrome at least.

Sorry no video!

As-yet unmerged work on [multiple marker selection](https://github.com/VEuPathDB/web-monorepo/pull/588), [popup placement](https://github.com/VEuPathDB/web-monorepo/pull/610) and [click handling](https://github.com/VEuPathDB/web-monorepo/pull/615) are not the cause (though note that the popup placement (now fixed) alternates every two seconds).

May be related to #573 ?

It's a recent regression though, just not sure exactly when/what caused it.

**Comment by moontrip** [comment]
I will check this out later

**Comment by moontrip** [comment]
@bobular I think that the problem is not popup in this case but actually refinedMarkers are kept regenerating due to continous change on because consolidatedMarkers. I think that it is related to your recent FlyTo work and honestly, I don't know well about it. So you can check this out.

https://github.com/VEuPathDB/web-monorepo/blob/bccb49074b3e76aa894114182d99a5612467bc28/packages/libs/components/src/map/SemanticMarkers.tsx#L173 

https://github.com/VEuPathDB/web-monorepo/blob/bccb49074b3e76aa894114182d99a5612467bc28/packages/libs/components/src/map/SemanticMarkers.tsx#L123
