### ISSUE TITLE
Bipartite Network: tooltips (or similar) to show correlation coefficient and pvalues for edges

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-monorepo#718]
If we can currently see these values for edges, its not in a way that was obvious to me when i was playing. but it does seem important enough information for an initial release to me..

**Comment by asizemore** [comment]
Worth thinking about this again. Initially we thought tooltips would be too difficult for edges because there would be so many and it'd be tough to get your cursor to be hovering over just the right one. But with all the filtering we do now that concern may not be so serious anymore.

**Comment by asizemore** [comment]
It's all coming back to me now. We also had specifically not planned anything for the edges because we thought it'd be much easier for the user to click the nodes. If we're planning this click-two-nodes-to-get-scatter-and-stats function, then would we _also_ want edges to be interactive? Probably not. Instead we'd say click the edges to get the scatter. As we use this app over the next month, we should think about if it's feasible to click edges. 

As a reminder, the user can intuit the correlation value via the stroke thickness (https://github.com/VEuPathDB/web-monorepo/pull/701). So if they've set the pvalue threshold, is it a min req for them to also see the actual value? I wouldn't think so, because all they _must_ know is that it passed the 0.05 significance goal they wanted. But again worth a discussion.
