### ISSUE TITLE
Map - multiple marker select: ctrl-click 3 markers in rapid succession, 2nd becomes unselected

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-monorepo#939]
As seen on qa.vectorbase.org and the production site

Likely something up with state management of `selectedMarkers` and `setSelectedMarkers`

**Comment by bobular** [comment]
It's *not* this effect causing the problem:

```
  // remove any selectedMarkers that no longer exist in the current markers
  useEffect(() => {
    if (setSelectedMarkers && selectedMarkers) {
      const prunedSelectedMarkers = selectedMarkers.filter((id) =>
        consolidatedMarkers.find(({ props }) => id === props.id)
      );

      if (prunedSelectedMarkers.length < selectedMarkers.length)
        setSelectedMarkers(prunedSelectedMarkers);
    }
  }, [consolidatedMarkers, selectedMarkers, setSelectedMarkers]);
```

What we likely need is a `setSelectedMarkers` that takes a functional argument (like setters from `useState()`) that provide access to the previous value.
But that is going to require a functional argument to the upstream `updateConfiguration` (`updateMarkerConfigurations` in `MapAnalysis`) which would require a functional arg to `appState.setMarkerConfigurations` which would need an overhaul of appState's `useSetter`).

**Comment by bobular** [comment]
See @moontrip's comment here:
https://github.com/VEuPathDB/web-monorepo/pull/937#issuecomment-2007719848

**Comment by dmfalke** [comment]
@moontrip feel free to close this, if you cannot reproduce this.

**Comment by moontrip** [comment]
@bobular @dmfalke I spend quite a lot of time investigating this, and I found the cause. It was not relevant to your initial guesses, but rather it is quite a simple reason.

When we implement marker click event to select markers, we had to distinguish single click from double click and resolved it by checking number of mouse clicks. It worked fine but there was another minor (?) issue that double click involved single click. In other words, if double clicking a marker, it is zoomed in but marker is selected. To avoid this, we used lodash debounce to make a term in between clicks (300 ms) https://github.com/VEuPathDB/web-monorepo/blob/db90846ac854c87b904d765ac1712c8aa042c799/packages/libs/components/src/map/BoundsDriftMarker.tsx#L330. This causes the issue of clicking 3 markers in rapid succession.

If just using handleClick callback instead of debounce function, then such a quick click of 3 markers just worked fine. By doing so, distinguishing single click from double click is no longer available, but it is mostly fine as double click of a marker involves zoom in event which also reset selectedMarkers: one glitch is that if a marker goes deep and no further zoom in cannot be made, which will make the marker be selected.

So, I think that we cannot satisfy all cases, so we have one of two choices: a) let's assume that clicking 3 markers consecutively is quite rare and will be hardly done by users. Since we also have area selection feature to select multiple markers, it may be okay to leave it as is; b) remove debounce function and leave the minor glitch as is.

**Comment by dmfalke** [comment]
Maybe we should have a switch to go between "zoom mode" and "select mode". Maybe holding the CTRL or CMD key can be a trigger for "select mode"?

**Comment by moontrip** [comment]
@dmfalke Thank you for your suggestion and that's interesting idea 👍 Indeed, we had a similar switch button (similar style with zoom buttons), so-called mousemode, before, but it was removed https://github.com/VEuPathDB/web-monorepo/pull/347. So, I am not quite sure if it is preferred by UI team 🤔

The latter part may be a bit tricky as we allow marker click to select (for the initial selection) without CTRL/CMD key and those keys are used for multiple marker selection or area selection (CTRL/CMD + Mouse click & drag)

**Comment by dmfalke** [comment]
I realize we had a mouse mode in the past, but it had a different meaning.

Here is my proposal:

**Select mode**
- Clicking a marker will toggle its selection state
- Click and drag will select every marker within the dragged rectangle
- We can have a button to clear selection
- Double click will not do anything special 

**Zoom mode** 
- Clicking a marker will zoom to its bounding box. Maybe this should still be a double click?
- Click and drag will zoom the the dragged rectangle


I might be missing other interactions, so take this all with a grain of salt. Maybe it can be a starting point?

**Comment by dmfalke** [comment]
I think I want to rescind what I said above, in my previous comment. I think it's very natural that a single click selects a marker, and that a double-click zooms to its bounding box.

Btw, I just checked, and there is a specific event for double click: https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event. We will still get two regular click events, but I think that might be okay.

**Comment by moontrip** [comment]
@dmfalke Thank you for your suggestions! 👍 BTW, I am afraid that I am a bit confused about your conclusion. So, no need to have two modes? It would be great if you can clarify this.

For the double click, actually the leaflet has built-in dblclick prop (within the context of eventHandlers prop) for marker and we are using it for double-click zoom behavior. I didn't look at leaflet code to see how the dblclick prop was actually implemented but I feel that it internally utilizes the double click event you mentioned.

**Comment by dmfalke** [comment]
I will try to clarify. I don't think we need two modes, for now. Furthermore, I agree with your conclusion that we can get rid of the debounce.

I didn't quite following this:

> one glitch is that if a marker goes deep and no further zoom in cannot be made, which will make the marker be selected.

In the case that a user double-clicks on a marker, I would expect the following to happen:
1. Marker is selected (first click)
2. Marker is deselected (second click)
3. The map zooms in (double-click)

This is due to the fact that the `dbclick` event fires after the two `click` events.

Is it possible we're using another debounce somewhere within the click handler's call stack?

I suppose another test is to remove the `dbclick` handler and see what happens when you double click a marker. I wonder if zooming in could be thrashing part of the state, causing the second marker selection state update to be lost. Or, maybe even more likely, the code that updates the marker selection state is using stale data, due to quick successions of clicks. This would go back to Bob's initial idea of allowing functional updates of the app state.

**Comment by moontrip** [comment]
@dmfalke Thank you for your detailed explanation 👍 As I mentioned, if we don't use debounce function that is used to distinguish single click from double click , everything works fine, including clicking 3 markers in rapid succession, double clock zoom in. The glitch I mentioned is, for your better understanding, please look at the following video capture - captured without using debounce. As you can see, I first tried clicking 3 markers in rapid succession (I had to try several times to click 3 markers correctly 😅), and then double clicking a marker several times until it reaches no further zoom-in. So, in the last stage, the marker remains selected. I think it is fine because our marker deselection scheme with respect to zoom is to deselect markers only if the marker is aggregated/de-aggregated. 

But if it reaches last stage, double click works like single click, and I described it as a glitch: also, you might see that when double clicking a marker to zoom in, it was firstly selected even if it was indeed a double click - but as I mentioned earlier, it is  covered by our zoom-based marker deselection scheme. Speaking with your three steps for better explanation, the leaflet's double click works like 1 and then 3, and no 2 happens: in other words, leaflet's double click involves single click but no second click. Many developers observed the same behavior (e.g., stack overflow) and have tried to distinguish single click from double click to avoid it. I followed some techniques from others' solutions (I adopted to check the number of clicks) but it was not sufficient for our purpose. That was the reason why I introduced debounce to solve our issue involving marker selection. And it is the only place we use the debounce for a click event.

For your last paragraph, if removing dbclick handler, then double click a marker will result in typical **map** zoom in, not marker-based zoom in: it is inherent feature of the leaflet. 

https://github.com/VEuPathDB/web-monorepo/assets/12802305/51927b2f-1f41-4fa4-981e-51278d148110

**Comment by dmfalke** [comment]
Thanks for following up, @moontrip. It sounds like leaflet is doing something to cause the second click event to not fire. I guess we will have to live with the glitch.

**Comment by moontrip** [comment]
@bobular Thank you for your suggestion. It sounds like you prefer to fix click 3 markers in rapid succession? If so, I will make a PR for that. Please correct me if I am wrong.

**Comment by bobular** [comment]
Hi @moontrip - what was my suggestion? I've not been following this thread as closely as I should have recently.

**Comment by bobular** [comment]
Thanks @moontrip 

I don't like the idea of the double-click behaviour being buggy when the user is fully zoomed in, so let's go for b) and live with it, for now at least.

Also, it's really hard to click fast enough to cause the three-click bug!

@dmfalke

**Comment by dmfalke** [comment]
Sounds like this is the best way to go. Thanks @moontrip!

**Comment by moontrip** [comment]
Thanks @bobular and @dmfalke for your kind attention on this ticket 👍

**Comment by bobular** [comment]
Decided to leave this for now.
