### ISSUE TITLE
eda-genomics wgcna: new title line on top of dataset name see mockup

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#973]
final name to be determined

<img width="791" alt="Screenshot 2024-03-28 at 6 49 23 PM" src="https://github.com/VEuPathDB/web-monorepo/assets/16354313/005ab285-8ede-42ec-b853-7569810bda98">

**Comment by dmfalke** [comment]
Note that this is only for genomic sites. Related, we should update the coreui theme used by genomics so that header elements use the same styling as the rest of the site. This can be configured in https://github.com/VEuPathDB/web-monorepo/blob/9725f2c542a8c25e190677b0d62f102eed6f4b6f/packages/sites/genomics-site/webapp/wdkCustomization/js/client/componentWrappers.jsx#L499
