### ISSUE TITLE
eda: do not show management dashboard on public studies

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/web-monorepo#994]
this is my suggestion..   it is clutter..  would remove from mbiome and genomic sites.  and in clinepi from all public studies. 

<img width="1279" alt="Screenshot 2024-04-10 at 9 47 23 AM" src="https://github.com/VEuPathDB/web-monorepo/assets/16354313/6e9d719c-551e-4242-94af-6dab14230a43">

**Comment by danicahelb** [comment]
`Management dashboard` button is currently missing on the qa sites (qa.clinepi & qa.restricted.clinepi)

Please bring back the management dashboard button on the QA sites ASAP, as this is how we give providers access to review their studies on the QA site.

For example, see MAL-ED (which is a protected study):
<img width="1462" alt="image" src="https://github.com/VEuPathDB/web-monorepo/assets/25450900/ead45b0d-7f68-4df6-a38b-627e51902d2f">

**Comment by danicahelb** [comment]
I talked to @aurreco-uga about adding the `management dashboard` button back to all studies

when we are getting a study ready for release, we add study team members to the dashboard so that they can see the study on the QA site. providers also should have the ability to add other study team members to the dashboard so that the right people can perform the QA. data restrictions don’t matter here… regardless of access level, this is how team members can see the study for QA purposes

Currently, a provider who logs into qa.clinepi is able to view ALL studies with public access, even those that have not yet been released. this is an oversight. any study that has not been released should only be accessible to members of the study team. This will need to be addressed in a separate ticket

Also, if funding is secured, there are plans to build out a system that allows study team members with manager permissions to edit the study details page, add additional tranches of data, modify labels, etc... for DIY/user datasets and possibly also for some aspects of curated studies. The management dashboard is how manager permissions are controlled, so we will need the button on all studies in the future.

**Comment by aurreco-uga** [comment]
https://github.com/VEuPathDB/web-monorepo/pull/1032

**Comment by aurreco-uga** [comment]
i stil think the solution is not that simple, clinepi wants the button everywhere including user datasets as explained by danica above. 
but we dont want to see it in mbiome or genomic sites.

**Comment by aurreco-uga** [comment]
frankly i would just  fix the bug for now.. so it only shows when needed.. 
danica describes a situation when it will be needed in public studies (in qa sites providers wont be able to see other providers studies even if public) 
 but that might not be the case for a while and i rather eliminate clutter..  and will be clue on how things are working.
